packages:
  - name: app
    type: yarn
    srcs:
      - "src/**"
      - package.json
      - webpack.config.js
      - tsconfig.json
    config:
      yarnLock: ${coreYarnLockBase}/../yarn.lock
      dontTest: true